### ISSUE TITLE
Website is not online

### ISSUE THREAD

**Issue by Sophie724** [Sophie724/css-validation-fixes#1]
I try to commit it again and also tried to rework it and redo this assignment but it still didn't work. :(

@carolsinc
![Screen Shot 2021-03-16 at 5 48 36 PM](https://user-images.githubusercontent.com/77297245/111384422-db1cd300-867f-11eb-9c9e-22d724fd3cb5.png)

**Comment by carolsinc** [comment]
If you look on github you can see that index.html has a capital i. You will need to rename it something completely different, commit and push it, then rename it index.html and commit and push again.

**Comment by Sophie724** [comment]
It works. Thank you so much:)

@carolsinc
